### ISSUE TITLE
High memory usage 

### ISSUE THREAD

**Issue by antoyo** [morganstanley/Xpedite#114]
When generating a report for a profiling that hit the probes many, many times, the ram usage goes very high (> 10 Gb).
Thanks to fix this issue.

**Comment by Mani-D** [comment]
Hi @antoyo ,

  This in an inherent limitation of python runtime (the number and footprint of objects created for representing samples). One solution is to use the txnFilter callback in your profileInfo.py to filter out transactions not of interest. This would reduce the amount of transactions processed.  Can you give it a try please ?

Thanks
Mani

**Comment by antoyo** [comment]
Is there a way to lower the sampling (I thought it was the goal of the `-H` option)?

**Comment by Mani-D** [comment]
Yes, the snippet in your comment would work. 

However, If you would like to even avoid capture or strictly control the samples captured, it can be done using the c++ embedded profiling [API](https://github.com/Morgan-Stanley/Xpedite/blob/master/include/xpedite/framework/Framework.H#L97).

[Here](https://github.com/Morgan-Stanley/Xpedite/blob/master/test/targets/EmbeddedApp.C#L52) is an example of an app using embedded profiler. The profile method lets you switch profiling on/off in a scope and thus can be used to capture only what's desired.

**Comment by antoyo** [comment]
That does not seem convenient to use this API.
It would be nice to have a way outside the application to sample the probes.
Using a filter does not help much because the extractor still loads everything.

**Comment by Mani-D** [comment]
Agreed.

Xpedite works on the concept of transactions (a collection of probes, that measure something meaningful). So sampling at probe level won't make much sense. If that's what is required, there are tooling that already accomplish that well (linux perf, Intel vtune). So I assume, we are talking about sampling transactions.

We also don't want to run any sampling logic in critical path, since that can add more overhead due to profiling. This could be done post processing in the [Samples loader](https://github.com/Morgan-Stanley/Xpedite/blob/master/bin/SamplesLoader.C#L39).

This would require enriching the samples loader to pick a subset of txn samples, from those captured. Or picking only transactions that exceed a latency limit. However we don't have that capability currently.

**Comment by robber-m** [comment]
Hello, I've been trying to test out integrating Xpedite into my application over the past few weeks. Recording seems to work efficiently with reasonably large numbers of transactions (hundreds of millions), but the analysis infrastructure totally falls over when digging into the data (takes on the order of hours and uses hundreds of gigabytes of RAM). Is this an expected limitation of the python infrastructure given your usage of xpedite profiling? I'm wondering if I'm using the toolset incorrectly or if it's really only intended to be used for smaller sampling periods.

**Comment by Mani-D** [comment]
> Hello, I've been trying to test out integrating Xpedite into my application (one you may have heard of :) over the past few weeks. Recording seems to work efficiently with reasonably large numbers of transactions (hundreds of millions), but the analysis infrastructure totally falls over when digging into the data (takes on the order of hours and uses hundreds of gigabytes of RAM for a 1.6 gigabyte samples data file). Is this an expected limitation of the python infrastructure given your usage of xpedite profiling? I'm wondering if I'm using the toolset incorrectly or if it's really only intended to be used for smaller sampling periods.
> 
> Some output of report generation from a < 5 minute benchmark run with [12701853 transactions]
> 


Thank you for  the details. This is a known issue for us. The python object model currently doesn't scale with millions of transaction. One stop gap solution to get around the scaling issue is to use txnFilter, to filter out uninteresting transactions.

The section in your report that runs for unspecified time is the bit that's creating the jupyter notebook. since we don't have visibility on it's implementation, we don't log % of progress there.
```
creating xpedite data directory /tmp/xpedite22r_wb5u/xpData
generating notebook redline-inrush.exe-2021-08-07-18:07:05.ipynb ->
```

We are actively working on a solution for the scalability issue. The Idea is to port the implementation to C++ with pybind11. The first [pull request](https://github.com/morganstanley/Xpedite/pull/162) the enable pybind11 is under development. Over the coming weeks, we will move more and more of the object model from python to C++ to provide better scalability.

Hope this helps.

**Comment by robber-m** [comment]
Thank you for your response!

> One stop-gap solution to get around the scaling issue is to use txnFilter, to filter out uninteresting transactions.

I was able to get meaningful information out of my benchmarks by applying filters to remove uninteresting transactions, but it leads to an awkward workflow for me. That said, I can keep pushing forward with this as-implemented to see if I can get to a point where Xpedite can add value for us :)

> The section in your report that runs for unspecified time is the bit that's creating the jupyter notebook. since we don't have visibility on its implementation, we don't log % of progress there.

> The Idea is to port the implementation to C++ with pybind11. The first pull request the enable pybind11 is under development. Over the coming weeks, we will move more and more of the object model from python to C++ to provide better scalability.

That sounds like a reasonable approach :) looking forward to testing it out when it's all in place!

I might be getting off-topic for this issue, so please let me know if you'd like me to ask this elsewhere.

I've been experimenting with Xpedite's support for top-down microarchitecture analysis, and I'm struggling to figure out the set of steps I need to take to drill into Topdown nodes that require more than 8 simultaneous performance counters. Is there a short guide for doing this available in the repo somewhere that I could take a look at (no worries if not, I can keep scrubbing through the python code to try and figure out my approach)?

I have played around with [toplev](https://github.com/andikleen/pmu-tools/wiki/toplev-manual) a bit in the past with some success, but it abstracts the end-user from the complexities of trying to multiplex performance counters (either during program execution or across benchmark runs). I haven't seen anything like this in Xpedite, but I might be missing something in my read of the python code. If you have any tips for performing top-down analysis with Xpedite, I'd really appreciate them!

Thanks,
Bobby McShane

**Comment by Mani-D** [comment]
Sorry about the delayed response.

> I've been experimenting with Xpedite's support for top-down microarchitecture analysis, and I'm struggling to figure out the set of steps I need to take to drill into Topdown nodes that require more than 8 simultaneous performance counters. Is there a short guide for doing this available in the repo somewhere that I could take a look at (no worries if not, I can keep scrubbing through the python code to try and figure out my approach)?

Topdown is implemented in a different way in Xpedite. 

Xpedite is not a sampling profiler, instead it lets you define transactions and build statistics / plots for a set of transaction.
In addition the focus is on drilling down to one or more transactions based on topdown / counters and looking at them in detail.  For example, we might want to compare our outlier transactions (95 or 99%ile) with our median transaction etc..

With this design, it's not feasible to multiplex performance counters, when the number of counters exceed the available combination of fixed + general purpose registers. The reason being, transactions are quite unique. They can execute different number of instructions and suffer from different bottlenecks. We may not get meaningful data by by multiplexing performance counters for different transaction and trying to combine them. It might also break the topdown ratios (may not add up to the expected %). Hence we don't support pmc multiplexing. This is represented by colors in the `xpedite topdown` command. If you run it in console, it will print the tree for the current processor architecture. The nodes that are not supported will be printed in red.

Thanks
Mani

**Comment by robber-m** [comment]
Thanks, Mani. I agree that multiplexing performance counters over the course of a single program's execution wouldn't make sense for our type of low-latency financial workloads which can be bursty or have fairly variable execution paths for each transaction. That said, I have a very deterministic benchmarking setup that consistently shows the same microarchitectural bottlenecks for my outlier transactions. I was hoping that Xpedite could multiplex the counters _across benchmark runs_ to help me drill down on the true bottleneck.

I have successfully done [something similar](https://github.com/andikleen/pmu-tools/wiki/toplev-manual#selecting-the-right-level-and-multiplexing) with `toplev` in the past by passing the `--no-multiplex` parameter. On second look, I may have mistakenly used the word "multiplex" here which could be leading to some confusion. I am really looking for a way to correlate counters across benchmark invocations rather than varying the set of sampled counters within a single benchmark.

All that said, it sounds like this isn't supported by Xpedite today (which is totally fine). Your response was helpful regardless in that I don't need to keep digging through the python code to see if I'm missing something.

Thanks again,
Bobby
