### ISSUE TITLE
Failed to run install.sh

### ISSUE THREAD

**Issue by kuibing126** [morganstanley/Xpedite#156]
![image](https://user-images.githubusercontent.com/75358276/114144369-d75f3200-9947-11eb-9f59-aa58b5b315ad.png)

Hi,
When I try to run ./install.sh,  always got "This backport is for Python 2.7 only". I'm sure that Python I'm using was version 2.7.

How can I handle it?

**Comment by Mani-D** [comment]
Issue resolved offline

**Comment by jimmylikes** [comment]
I got the same error when do install, could you please show some light how is this solved?

**Comment by becantwell** [comment]
Hi, the resolution for this issue was to create a virtual environment with all of the xpedite dependencies installed in it, by running:
`install.sh`
in the xpedite root directory. Once you run this command and the virtual environment is ready to use, you can create an alias in your shell to start xpedite using this virtual environment instead of the default python environment in your linux system:
`alias xpedite="PATH=`pwd`/install/runtime/bin `pwd`/scripts/bin/xpedite"`
If you then run xpedite with this alias from the root directory, it should solve the problem and complete the profile.

**Comment by jimmylikes** [comment]
thanks，it works for me now after reinstalling all dependent python related components
